// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-3dJ5KrBMqNNiT58bGFOvr9du0_r7q1M',
    appId: '1:467740330479:web:ca1f9d511c9dbf2d684e1a',
    messagingSenderId: '467740330479',
    projectId: 'noteapp-aea6f',
    authDomain: 'noteapp-aea6f.firebaseapp.com',
    storageBucket: 'noteapp-aea6f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWJ4iUtdPsiQ9QFxFiLgDEMLZpyr8fOQ',
    appId: '1:467740330479:android:3af5d30818e1d31d684e1a',
    messagingSenderId: '467740330479',
    projectId: 'noteapp-aea6f',
    storageBucket: 'noteapp-aea6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_oDDWQZ0co7VtvAyzAvUr4GSmufFi4Ug',
    appId: '1:467740330479:ios:ebb85c1308070c98684e1a',
    messagingSenderId: '467740330479',
    projectId: 'noteapp-aea6f',
    storageBucket: 'noteapp-aea6f.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_oDDWQZ0co7VtvAyzAvUr4GSmufFi4Ug',
    appId: '1:467740330479:ios:ebb85c1308070c98684e1a',
    messagingSenderId: '467740330479',
    projectId: 'noteapp-aea6f',
    storageBucket: 'noteapp-aea6f.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-3dJ5KrBMqNNiT58bGFOvr9du0_r7q1M',
    appId: '1:467740330479:web:7e165034c274656c684e1a',
    messagingSenderId: '467740330479',
    projectId: 'noteapp-aea6f',
    authDomain: 'noteapp-aea6f.firebaseapp.com',
    storageBucket: 'noteapp-aea6f.firebasestorage.app',
  );
}
